name: Run Code quality checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  files_status:
    name: check for file changes in JS/TS/SCSS/ or accounts app
    runs-on: ubuntu-latest
    outputs:
      jstsChanged: ${{ steps.filesStatus.outputs.jstsChanged }}
      cssChanged: ${{ steps.filesStatus.outputs.cssChanged }}
      accountsAppChanged: ${{ steps.filesStatus.outputs.accountsAppChanged }}
    steps:
      - uses: actions/checkout@v3
      - name: Get all changed files and join them using comma separator
        id: changed_files
        uses: tj-actions/changed-files@v35.6.0
        with:
          separator: ','
      - name: Set filesStatus output to a variable
        id: filesStatus
        run: |
          echo "jstsChanged=${{ github.event_name != 'push' && (contains(steps.changed_files.outputs.all_changed_files, '.ts') || contains(steps.changed_files.outputs.all_changed_files, '.js')) }}" >> $GITHUB_ENV
          echo "cssChanged=${{ github.event_name != 'push' && contains(steps.changed_files.outputs.all_changed_files, '.scss') }}" >> $GITHUB_ENV
          echo "accountsAppChanged=${{ github.event_name != 'push' && contains(steps.changed_files.outputs.all_changed_files, 'app-v2/apps/accounts/src') }}" >> $GITHUB_ENV
      - name: Cache node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        name: Install modules
        run: npm ci
    
  eslint:
    name: eslint runner
    runs-on: ubuntu-latest
    needs: files_status
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        name: Install modules
        run: npm ci
      - name: Fetch the base branch, so we can use `git diff`
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      - name: Run ESLint on modified code
        env:
          ESLINT_PLUGIN_DIFF_COMMIT: ${{ github.event.pull_request.base.ref }}
        run: npx --no-install eslint --ext .js,.ts .

  stylelint:
    name: stylelint runner
    runs-on: ubuntu-latest
    needs: files_status
    # Run the job only if there are changes in SCSS files
    if: ${{ needs.files_status.outputs.cssChanged == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: '**/*.scss'
          fail_on_error: true
     
  accounts_unit_test:
    name: accounts unit test
    runs-on: ubuntu-latest
    needs: files_status
    
    # Run the job only if there are changes in TS/HTML files
    if: ${{ needs.files_status.outputs.accountsAppChanged == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run unit test for accounts app 
        run: |
          cd app-v2
          # We generate config.ts file during app build based on the environment(flow or fyle app).
          # Without the file, unit test throws compilation errors. To resolve the issue, either build the whole app
          # or run the below command.
          node ./scripts/set-target-config.js --targetApp fyle --appName accounts
          npm run accounts-test
      - name: Unit Test Coverage
        uses: fylein/comment-test-coverage@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app-v2/coverage/apps/accounts/coverage-summary.json
          title: Accounts Unit Test Coverage
