name: Run Code quality checks

on:
  pull_request:
    branches: master

  push:
    branches: master

jobs:
  files_status:
    name: check for file changes in JS/TS/SCSS/HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get all changed files and join them using comma separator
        id: changed_files
        uses: tj-actions/changed-files@v35.6.0
        with:
          separator: ','
          since_last_remote_commit: true
      - name: Set filesStatus output to a variable
        id: filesStatus
        run: |
          if [[ ${{ github.event_name }} != 'push' ]]; then
            echo " ${{ steps.changed_files.outputs.all_changed_files }}"
          fi
      - name: Testing actions 
        uses: ./.github/actions/unit-test-action
        with:
          app-name: 'accounts'
          github-token: ${{ secrets.GITHUB_TOKEN }}
