name: Run Code quality checks

on:
  pull_request:
    branches: master

  push:
    branches: master

jobs:
  files_status:
    name: check for file changes in JS/TS/SCSS/HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing actions 
        uses: ./.github/actions/unit-test-action
        with:
          app-name: 'accounts'
          github-token: ${{ secrets.GITHUB_TOKEN }}
