name: Run Code quality checks

on:
  pull_request:
    branches: master

  push:
    branches: master

jobs:
  files_status:
    name: check for file changes in JS/TS/SCSS/HTML
    runs-on: ubuntu-latest
    outputs:
      jstsChanged: ${{ steps.filesStatus.outputs.jstsChanged }}
      cssChanged: ${{ steps.filesStatus.outputs.cssChanged }}
      accountsAppChanged: ${{ steps.filesStatus.outputs.accountsAppChanged }}
      spenderAppChanged: ${{ steps.filesStatus.outputs.spenderAppChanged }}
      adminAppChanged: ${{ steps.filesStatus.outputs.adminAppChanged }}
      settingsAppChanged: ${{ steps.filesStatus.outputs.settingsAppChanged }}
      upsertExpenseAppChanged: ${{ steps.filesStatus.outputs.upsertExpenseAppChanged }}
    steps:
      - name: Testing actions 
        uses: ./.github/actions/unit-test-action
        with:
          app-name: 'accounts'
          github-token: ${{ secrets.GITHUB_TOKEN }}