name: Cache node modules
on:
  push:
    branches: master
jobs:
  build:
    name: cache node_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup node
        with:
          node-version: 16
      - name: Cache node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        name: Install modules
        run: npm ci
