name: Create Release Branch 
on:
  push:
    branches: test-secrets

jobs:
  create-release-branch:
    name: Create release branch for Fyle app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Run script to create release branches for fyle and flow
        run: |
          node create-release-branch.js ${{ secrets.SLACK_DEPLOY_WEB_HOOK_URL }}

