name: Delete Unused Caches
on:
  push:
    branches: master
permissions:
  actions: write
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.pull_request.number }}/merge