name: Deploy to netlify
on:
  push:
    branches: test-secrets

jobs:
  netlify-non-prod-deployment:
    runs-on: ubuntu-latest
    environment: netlify-non-prod-deployment
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get commit author email
      run: |
        response=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "https://api.github.com/repos/fylein/commits/${{ github.sha }}")
        email=$(echo "${response}" | jq -r '.commit.author.email')
      echo "Commit author email: ${email}"

    - name: Run script to auto deploy
      run: |
        BRANCH=$(echo "${{ github.ref }}")
        BRANCH=${BRANCH#refs/heads/}
        COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})
        AUTHOR=${{ github.actor }}
        EMAIL==$(git log -1 ${{ github.sha }} --pretty=format:'%ae')
        node ./scripts/netlify-deployment.js ${{ secrets.NETLIFY_BUILD_HOOKS }} "$BRANCH" "$EMAIL" "$COMMIT_MSG"
