name: My Workflow
on:
  pull_request:
    branches: master

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: My Step
      uses: actions/github-script@v6
      with:
        script: |
          const NETLIFY_BUILD_HOOKS = JSON.parse(`${{ secrets.NETLIFY_BUILD_HOOKS }}`);
          const fyleMasterBuildHook = NETLIFY_BUILD_HOOKS.fyle.master;
          console.log(fyleMasterBuildHook);