name: My Workflow
on:
  push:
    branches: test-secrets

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: My Step
      run: |
        BRANCH=$(echo "${{ github.ref }}")
        BRANCH=${BRANCH#refs/heads/}
        COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})
        AUTHOR=${{ github.actor }}
        node ./scripts/netlify-deploy.js ${{ secrets.NETLIFY_BUILD_HOOKS }} "$BRANCH" "$AUTHOR" "$COMMIT_MSG" 2>&1
    - name: Check if script succeeded
      if: ${{ success() }}
      run: |
        echo "Script succeeded"
    - name: Check if script failed
      if: ${{ failure() }}
      run: |
        echo "Script failed"