name: My Workflow
on:
  pull_request:
    branches: [ master ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: My Step
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: echo $MY_SECRET
