name: My Workflow
on:
  pull_request:
    branches: master

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: My Step
      run: |
        ./scripts/netlify-deploy.js ${{ secrets.NETLIFY_BUILD_HOOKS }} ${{ github.head_ref }}