name: My Workflow
on:
  pull_request:
    branches: master

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: My Step
      uses: actions/github-script@v5
      with:
        script: |
          const envSecret = await github.rest.actions.getEnvironmentSecrets({
            repository_id: ${{ github.repository }},
            environment_name: 'production'
          })
          console.log(envSecret)