name: My Workflow
on:
  pull_request:
    branches: master

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: My Step
      run: |
        ./scripts/netlify-deploy.js ${{ secrets.NETLIFY_BUILD_HOOKS }} ${{ github.head_ref }}