name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v2
      - name: Run reviewdog
        uses: reviewdog/action-eslint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN_1 }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN_1 }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'