name: Run ESLint on modified code
on:
  pull_request:
    branches: master
    paths:
jobs:
  build:
    name: eslint runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get all changed files and join them using comma separator
        id: changed-files
        uses: tj-actions/changed-files@v35.6.0
        with:
          separator: ','
      - name: Set Output Variable
        id: fileChangeStatus
        run: echo "changed=${{contains(steps.changed-files.outputs.all_changed_files, '.ts') ||  contains(steps.changed-files.outputs.all_changed_files, '.js')}}" >> "$GITHUB_OUTPUT"
      - name: Echo output variable
        run: echo "Output variable value -> ${{ steps.fileChangeStatus.outputs.changed }}"
        # run: echo "::set-output name=hasFilesChanged::${{contains(steps.changed-files.outputs.all_changed_files, '.ts') ||  contains(steps.changed-files.outputs.all_changed_files, '.js')}}"
      # - name: Check steps values
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       console.log({steps})
      - name: Cache node modules
        if: ${{ steps.fileChangeStatus.outputs.changed }}
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-cache.outputs.cache-hit != 'true' && steps.fileChangeStatus.outputs.changed }}
        name: Install modules
        run: npm ci
      - name: Fetch the base branch, so we can use `git diff`
        if: ${{ steps.fileChangeStatus.outputs.changed }}
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      - name: Run ESLint on modified code
        if: ${{ steps.fileChangeStatus.outputs.changed }}
        env:
          ESLINT_PLUGIN_DIFF_COMMIT: ${{ github.event.pull_request.base.ref }}
        run: npx --no-install eslint --ext .js,.ts .