name: Run ESLint on modified code
on:
  pull_request:
    branches: master
    paths:
jobs:
  eslint:
    name: eslint runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get all changed files and join them using comma separator
        id: changed-files
        uses: tj-actions/changed-files@v35.6.0
        with:
          separator: ','
      - if: ${{ contains(steps.changed-files.outputs.all_changed_files, '.ts') }}
        steps: 
        - name: Cache node modules
          uses: actions/cache@v3
          id: node-cache
          with:
            path: '**/node_modules'
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
          name: Install modules
          run: npm ci && cd app-v2 && npm ci
        - name: Fetch the base branch, so we can use `git diff`
          run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}