name: reviewdog
on: [pull_request]
env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN_1 }}
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v2
      - run: echo $REVIEWDOG_GITHUB_API_TOKEN
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN_1 }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'