name: Run ESLint on modified code
on:
  pull_request:
    branches: master

permissions: 
  pull-requests: write
  contents: read
  statuses: write
jobs:
  build:
    name: eslint runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get all changed files and join them using comma separator
        id: changed-files
        uses: tj-actions/changed-files@v35.6.0
        with:
          separator: ','
      - if: ${{ contains(steps.changed-files.outputs.all_changed_files, '.js') || contains(steps.changed-files.outputs.all_changed_files, '.ts') }}
          name: Cache node modules
          uses: actions/cache@v3
          id: node-cache
          with:
            path: '**/node_modules'
            key: node-modules-${{ hashFiles('**/package-lock.json') }}