name: Run ESLint on modified code
on:
  pull_request:
    branches: master
jobs:
  build:
    name: eslint runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Pick Cached node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Fetch the base branch, so we can use `git diff`
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      - name: Run ESLint on modified code
        env:
          ESLINT_PLUGIN_DIFF_COMMIT: ${{ github.event.pull_request.base.ref }}
        run: npx --no-install eslint --ext .js,.ts .
      - name: Delete node_modules
        run: gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/OWNER/REPO/actions/cache/usage