name: Run ESLint on modified code

on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write
  contents: read
  statuses: write

jobs:
  eslint-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.6.0
      - name: Check if changed files include JavaScript or TypeScript files
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, '.js') || contains(steps.changed-files.outputs.all_changed_files, '.ts') }}
        run: |
          # Cache node modules
          uses: actions/cache@v2
          id: cache-node-modules
          with:
            path: '**/node_modules'
            key: node-modules-${{ hashFiles('**/package-lock.json') }}

          # Install modules if not cached
          name: Install modules if not cached
          run: npm ci
          if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Fetch base branch for git diff
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Run ESLint on modified code
        env:
          ESLINT_PLUGIN_DIFF_COMMIT: ${{ github.event.pull_request.base.ref }}
        run: npx eslint --ext .js,.ts .
