name: Run ESLint on modified code
on:
  pull_request:
    branches: master
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
jobs:
  build:
    name: Run eslint with reviewdog
    uses: reviewdog/action-eslint@v1.16.1
