name: Run ESLint on your changes only
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ESlint Runner Action
        uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint
