name: Run unit test only on app-v2 folder changes
on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ","
      - name: List all changed files
        run: |
            echo "$steps.changed-files.outputs.all_changed_files"
          done
      - name: Cache node modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        name: Install modules
        run: npm ci --save-dev
      - name: Run unit test for accounts app
        if: ${{ startsWith(steps.changed-files.outputs.all_changed_files, 'src') }}
        run: |
          cd app-v2
          npm run accounts-test